# Generated by Django 5.0.6 on 2024-08-23 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('reports', '0006_remove_report_post_id_report_post'),
        ('userprofile', '0002_alter_userprofile_age_alter_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('post', 'Post'), ('user_profile', 'User Profile')], default='post', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile'),
        ),
        migrations.AlterField(
            model_name='report',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.TextField(),
        ),
    ]
