# Generated by Django 5.0.6 on 2024-08-23 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('reports', '0008_remove_report_post_alter_report_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('post', 'Post'), ('user_profile', 'User Profile')], default='post', max_length=20),
        ),
    ]
